# Task Configuration File

process_perception:
  description: "Process and structure incoming information"
  agent: perception_agent
  context:
    stage: "initial_processing"
  next_tasks:
    - manage_working_memory

manage_working_memory:
  description: "Maintain and update active information"
  agent: working_memory_agent
  next_tasks:
    - analyze_patterns

analyze_patterns:
  description: "Identify and analyze patterns"
  agent: pattern_analysis_agent
  next_tasks:
    - control_attention

control_attention:
  description: "Filter and prioritize information"
  agent: attention_control_agent
  next_tasks:
    - apply_reasoning

apply_reasoning:
  description: "Apply logical analysis"
  agent: reasoning_agent
  next_tasks:
    - integrate_knowledge

integrate_knowledge:
  description: "Connect with existing knowledge"
  agent: knowledge_integration_agent
  next_tasks:
    - synthesize_decision

synthesize_decision:
  description: "Generate final decision or response"
  agent: decision_synthesis_agent